### ISSUE TITLE
ice-2.4.5 does not compile with the Debian kernel 4.19.0-27

### ISSUE THREAD

**Issue by a-vasilishin** [intel/ethernet-linux-ice#51]
Hello There is a problem with  ice-2.4.5. It does not compile with the Debian kernel 4.19.0-27, previous version 2.3.15 compile fine.

```
# LANG=C make
make  ccflags-y="-std=gnu11 -Wno-nested-externs -std=gnu11  -DUSE_INTEL_AUX_BUS" -C "/lib/modules/4.19.0-27-amd64/source" CONFIG_=m CONFIG_MODULE_SIG=n CONFIG_MODULE_SIG_ALL= M="/opt/ice-2.4.5/src"   NEED_AUX_BUS="2"  modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.0-27-common'
make[2]: Entering directory '/usr/src/linux-headers-4.19.0-27-amd64'
  CC [M]  /opt/ice-2.4.5/src/ice_main.o
In file included from <command-line>:
/usr/src/linux-headers-4.19.0-27-common/include/linux/compiler_types.h:222:23: error: expected ')' before '__attribute__'
 #define __section(S)  __attribute__((__section__(#S)))
                       ^~~~~~~~~~~~~
/usr/src/linux-headers-4.19.0-27-common/include/linux/init.h:51:20: note: in expansion of macro '__section'
 #define __initdata __section(.init.data)
                    ^~~~~~~~~
/opt/ice-2.4.5/src/kcompat.h:77:30: note: in expansion of macro '__initdata'
  ___ADDRESSABLE(init_module, __initdata);
                              ^~~~~~~~~~
/opt/ice-2.4.5/src/kcompat.h:85:1: note: in expansion of macro 'orig_module_init'
 orig_module_init(kc_module_init_fn)
 ^~~~~~~~~~~~~~~~
/opt/ice-2.4.5/src/ice_main.c:8091:1: note: in expansion of macro 'module_init'
 module_init(ice_module_init);
 ^~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-4.19.0-27-common/scripts/Makefile.build:309: /opt/ice-2.4.5/src/ice_main.o] Error 1
make[2]: *** [/usr/src/linux-headers-4.19.0-27-common/Makefile:1577: _module_/opt/ice-2.4.5/src] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.19.0-27-amd64'
make[1]: *** [Makefile:153: sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-27-common'
make: *** [Makefile:180: all] Error 2
```
