### ISSUE TITLE
[bug] ice 1.15.4 doesn't compile with Linux 6.11-rc6

### ISSUE THREAD

**Issue by JonKohler** [intel/ethernet-linux-ice#9]
Hey all - thanks for the most recent 1.15.4 update, that fixed up a ton of compile issues that I saw with 6.11, however, one lingers on. 

### Driver Tag/Commit

https://github.com/intel/ethernet-linux-ice/releases/tag/v1.15.4

### Custom Code

No

### OS Platform and Distribution

Linux 6.11-rc6 (431c1646e1f8) - https://github.com/torvalds/linux/tree/v6.11-rc6

### Bug description

Intel ice out of tree driver 1.15.4 does not compile with latest mainline, 6.11-rc6

Breakage was introduced by this commit and you can see that in-tree ice_ptp.c was fixued up there: 
https://github.com/torvalds/linux/commit/ff985c759778986f55cbc557055fbeb84ee833eb

### Reproduction steps

```bash
1. Pull latest rc tag from Linux tree (https://github.com/torvalds/linux/tree/v6.11-rc6)
2. Try to compile with 1.15.4
3. Watch it go kaboom with error noted in logs below
```

### Expected Behavior

It compiles

### Actual Behavior

It does not compile

### Additional Data

```bash
Using mockbuild environment with el8 based userspace, and distro compiler (GCC 8.5 distro managed)
```

### Relevant log output

```shell
[ice] /builddir/build/BUILD/ice-1.15.4/src/ice_ptp.c: In function 'ice_ptp_aux_dev_to_owner_pf':
[ice] /builddir/build/BUILD/ice-1.15.4/src/ice_ptp.c:5221:10: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
[ice]   aux_drv = to_auxiliary_drv(aux_dev->dev.driver);
[ice]           ^
[ice] cc1: all warnings being treated as errors
```

**Comment by JonKohler** [comment]
cc @lczapnik @jbrandeb @rdower - not sure how the notifications are setup on this project, so tagging you directly. The fixup looks like a 1 liner, so we can fix that in our build system, though I'd imagine there'd have to be some formal compat-layer stuff to fix this up properly?

**Comment by pkitszel** [comment]
We do test our drivers against kernels, that were packaged by main OS Vendors.

In this (and similar) cases, your kernel is simply newer than our test base. We are going to fix this by next release.

**Comment by JonKohler** [comment]
Great! Thanks @pkitszel. I won't hold you to an exact date, but was curious when that is projected for? The last few Intel releases seemed to be on a 4-6 week release cadence, is that still the expectation going forward?

**Comment by JonKohler** [comment]
Hi @lczapnik - I see you closed this issue, but I do not see a new releases tag for this repo. Is that incoming shortly?
